### ISSUE TITLE
Minor issues to fix

### ISSUE THREAD

**Issue by swkrish** [AzureADQuickStarts/AppModelv2-SinglePageApp-AngularJS-DotNet#1]
1. Consider shortening the file names. Fails on build on VS if path is too long.
2. https://github.com/AzureADQuickStarts/AppModelv2-SinglePageApp-AngularJS-DotNet/blob/complete/TodoSPA/index.html#L32: There is an extra space before "userInfo.isAuthenticated".
3. If you use the manual route of downloading adal.js and adal-angular.js, you need to replace the following lines in "index.html" with the right path.

Replace

```

<script src="App/bower_components/dist/adal.min.js"></script>
<script src="App/bower_components/dist/adal-angular.min.js"></script>
```

With 

```

<script src="App/lib/adal-angular-experimental/dist/adal.min.js"></script>
<script src="App/lib/adal-angular-experimental/dist/adal-angular.min.js"></script>

```

**Comment by jmprieur** [comment]
this sample was archived
